### ISSUE TITLE
中文註解導致 SyntaxError

### ISSUE THREAD

**Issue by lyenliang** [csterryliu/Legal-Attest-Letter-Generator#1]
哈囉，我發現用 python 2.7 執行 `tw-lal-generator.py --help` 會發生 `SyntaxError: Non-ASCII character '\xe5'`。有 2 種解法：
1. 換用 python 3 
2. 在有中文註解的檔案第一行加上 `# -*- coding: utf-8 -*-`

**Comment by csterryliu** [comment]
Hi! Yen!! Thanks for your feedback!!!
我目前的 Master Branch 已經改寫成只支援 Python 3，如果你需要用 Python 2 ，可以用  Py2 這個 Branch。但是 Py2 沒有做重構。

也許未來我會研究怎麼兼容 Python 2。但接下來我想先 Release 含有 GUI 的版本，所以這個可能以後再看囉

**Comment by lyenliang** [comment]
了解，原來是這樣 XD

**Comment by lyenliang** [comment]
我本來在想有沒有可能做成網頁版的，因為之前我有接觸 Ruby on Rails，想說說不定可以用 Ruby on Rails 把這個功能在網頁上實現
